"""empty message

Revision ID: 1f47e1810272
Revises: 7562b4de7307
Create Date: 2019-08-15 15:21:01.842051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f47e1810272'
down_revision = '7562b4de7307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bu_name', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_unit')
    # ### end Alembic commands ###
