"""empty message

Revision ID: 7f590e6b7b08
Revises: 1f47e1810272
Create Date: 2019-08-15 15:28:18.339483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f590e6b7b08'
down_revision = '1f47e1810272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('business_unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'business_unit', ['business_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'business_unit_id')
    # ### end Alembic commands ###
